### ISSUE TITLE
How to init

### ISSUE THREAD

**Issue by mikkokam** [Kinvey/html5-sdk#1]
Trying to get started with the Beta.
The [Getting Started](http://devcenter.kinvey.com/html5-v3.0/guides/getting-started)
says to add the js from CDN and then call Kinvey.init.

Works fine for the current, but beta fails.

This throws Kinvey.init is not a function, see the Pen below:
http://codepen.io/mikkokam/pen/32468d707360ab0dc280856244b1f0d7

**Comment by thomasconner** [comment]
Looks like the Kinvey namespace is not being exporting correctly. We are looking into this issue.

**Comment by thomasconner** [comment]
This issue has been fixed with the latest release. Please use 3.0.0-beta.8.

**Comment by mikkokam** [comment]
Excellent, thanks! Got it to init and ping.

Is it possible that Kinvey.User is still not exported properly? Trying to add the next steps / ping is OK but login fails:

http://codepen.io/mikkokam/pen/BjXZQZ/

Implemented according to:
http://devcenter.kinvey.com/html5-v3.0/guides/users#login

´Kinvey.User.login is not a function´

**Comment by thomasconner** [comment]
It is but the User guide in the dev center is the last thing that needs to be updated. To properly login you must create an instance of the user class. See the example below:

``` javascript
var user = new Kinvey.User();
var promise = user.login('<username>', '<password>').then(function(user) {
  ...
});
```

When we released beta, the user API was not finalized and still a work in progress. Now that it has been settled the next step will be to update the documentation.

We mostly likely will also add a class level login method to the `User` class so that you could do as you did in the example you provided.

**Comment by mikkokam** [comment]
Thanks - makes sense.
All good now.

Seems to work with Babel and ES6 as well. 
ES6 classes with dotted namespacing might look a bit odd, but seems even React still uses them.
